### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by dpsoft** [kamon-io/kamon-agent#26]
if we execute this command in the console  `java -javaagent:kamon-agent.jar` we get:

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.NoClassDefFoundError: scala/Product
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at kamon.agent.BuildInfo.version(BuildInfo.scala)
	at kamon.agent.util.banner.AgentBanner.show(AgentBanner.java:48)
	at kamon.agent.AgentEntryPoint.lambda$start$0(AgentEntryPoint.java:44)
	at kamon.agent.util.AgentUtil.timed(AgentUtil.java:33)
	at kamon.agent.util.AgentUtil.withTimeSpent(AgentUtil.java:37)
	at kamon.agent.AgentEntryPoint.start(AgentEntryPoint.java:42)
	at kamon.agent.AgentEntryPoint.premain(AgentEntryPoint.java:53)
	at kamon.agent.KamonAgent.premain(KamonAgent.java:34)
	... 6 more
Caused by: java.lang.ClassNotFoundException: scala.Product
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 26 more
FATAL ERROR in native method: processing of -javaagent failed
[1]    19246 abort (core dumped)  java -javaagent:kamon-agent.jar

this error is because the `sbt-buildinfo` plugin introduce a scala dependency :(

here: https://github.com/sbt/sbt-buildinfo/pull/98 a solution but not merged

**Comment by cristianspinetta** [comment]
Fix by #31
